#!/usr/bin/python3

import sys
import requests
from pathlib import Path

BASE_URL = 'https://adventofcode.com/2021/day/{}/input'
if len(sys.argv) < 2:
    sys.stderr.write('missing date parameter\n')
    sys.exit(1)

cookie_key = None
if not Path('.COOKIE_KEY').exists():
    sys.stderr.write('no cookie provided\n')
    sys.exit(1)
with open('.COOKIE_KEY') as cookie:
    cookie_key = cookie.read()
    cookie.close()

Path('in').mkdir(exist_ok=True)
if Path('in/day{}'.format(sys.argv[1])).exists():
    sys.stdout.write('input file already retrieved\n')
    sys.exit(0)

sys.stdout.write('retrieving input file...\n')
url = BASE_URL.format(sys.argv[1])
r = requests.get(url, headers={'Cookie': cookie_key})
if r.status_code != 200:
    sys.stderr.write('input file is not yet available\n')
    sys.exit(1)
with open('in/day{}'.format(sys.argv[1]), 'x') as f:
    f.write(r.text)
    f.close()
sys.stdout.write('input file fetched\n')
sys.exit(0)
