#!/bin/bash

DAY=$1

./fetch_input $DAY
INPUT_FAILED=$?
if [ $INPUT_FAILED -eq 1 ]; then
	exit 1
fi

mkdir -p out
ghc -o out/Day${DAY} src/Day${DAY}.hs
COMPILE_FAILED=$?
if [ $COMPILE_FAILED -eq 1 ]; then
	exit 1
fi

time ./out/Day${DAY}
